# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileDeal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_button.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.file_button.setObjectName("file_button")
        self.file_input = QtWidgets.QLineEdit(self.centralwidget)
        self.file_input.setGeometry(QtCore.QRect(240, 100, 281, 20))
        self.file_input.setObjectName("file_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 130, 91, 16))
        self.label.setObjectName("label")
        self.index_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.index_text.setGeometry(QtCore.QRect(150, 160, 371, 121))
        self.index_text.setObjectName("index_text")
        self.index_box = QtWidgets.QSpinBox(self.centralwidget)
        self.index_box.setGeometry(QtCore.QRect(310, 130, 42, 22))
        self.index_box.setProperty("value", 1)
        self.index_box.setObjectName("index_box")
        self.file_show = QtWidgets.QPushButton(self.centralwidget)
        self.file_show.setGeometry(QtCore.QRect(430, 130, 91, 23))
        self.file_show.setObjectName("file_show")
        self.choose_step = QtWidgets.QComboBox(self.centralwidget)
        self.choose_step.setGeometry(QtCore.QRect(150, 300, 191, 22))
        self.choose_step.setObjectName("choose_step")
        self.choose_step.addItem("")
        self.choose_step.addItem("")
        self.choose_step.addItem("")
        self.choose_step.addItem("")
        self.save_file = QtWidgets.QPushButton(self.centralwidget)
        self.save_file.setGeometry(QtCore.QRect(450, 300, 75, 23))
        self.save_file.setObjectName("save_file")
        self.index1 = QtWidgets.QSpinBox(self.centralwidget)
        self.index1.setGeometry(QtCore.QRect(350, 300, 42, 22))
        self.index1.setProperty("value", 1)
        self.index1.setObjectName("index1")
        self.index2 = QtWidgets.QSpinBox(self.centralwidget)
        self.index2.setGeometry(QtCore.QRect(400, 300, 42, 22))
        self.index2.setProperty("value", 1)
        self.index2.setObjectName("index2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_button.setText(_translate("MainWindow", "文件导入"))
        self.label.setText(_translate("MainWindow", "标题所在行为"))
        self.file_show.setText(_translate("MainWindow", "获取文件信息"))
        self.choose_step.setItemText(0, _translate("MainWindow", "选择操作"))
        self.choose_step.setItemText(1, _translate("MainWindow", "合并模块与标题"))
        self.choose_step.setItemText(2, _translate("MainWindow", "合并预置条件与操作步骤"))
        self.choose_step.setItemText(3, _translate("MainWindow", "拆分操作步骤与输入数据"))
        self.save_file.setText(_translate("MainWindow", "保存"))
